### ISSUE TITLE
Add permissions for EKS nodes to allow them to use Container Insights

### ISSUE THREAD

**Issue by davejrocks** [Cloud-42/terraform-aws-eks#8]
We are setting up AWS Container Insights to monitor our cluster but this requires some additional permissions for the EKS nodes.

There are 2 options:
Attach the  CloudWatchAgentServerPolicy Managed Service policy 
Add the permissions to one of the existing custom policies you have configured.

I think the second option would be the cleanest and suggest modifying the "node_logging_policy" to add the required permissions as below:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "cloudwatch:PutMetricData",
                "ec2:DescribeVolumes",
                "ec2:DescribeTags",
                "logs:PutLogEvents",
                "logs:DescribeLogStreams",
                "logs:DescribeLogGroups",
                "logs:CreateLogStream",
                "logs:CreateLogGroup"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ssm:GetParameter"
            ],
            "Resource": "arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*"
        }
    ]
}

Let me know if you think this makes sense or if there is a better way to do this. Thanks

**Comment by Cloud-42** [comment]
Hi Dave, thanks for the feature request. I've added the CloudWatchAgentServerPolicy policy as an optional attachment. Changes are on the branch ContainerInsightsPermissions to facilitate testing. To test the changes set the branch by using :   

?ref=ContainerInsightsPermissions

To enable attaching of the CloudWatchAgentServerPolicy please also set :   

enable_CWAgentPolicy = "1"
